- name: Install system dependencies and configure NVM/Pyenv
  hosts: shoulderpi

  tasks:
    - name: Install apt dependencies
      import_tasks: tasks/apt_dependencies.yaml

    - name: Install NVM
      import_tasks: tasks/install_nvm.yaml

    - name: Install Pyenv
      import_tasks: tasks/install_pyenv.yaml

    - name: Install pipx and add pipx dependencies
      import_tasks: tasks/pipx.yaml
