- name: Copy Files
  become: yes # Runs commands with sudo
  hosts: cameras
  tasks:
    - name: Copy Gray Code patterns
      ansible.builtin.copy:
        src: graycode_patterns
        dest: .

    - name: Copy python snap.py
      ansible.builtin.copy:
        src: snap.py
        dest: snap.py

    - name: Copy python camera_server.py
      ansible.builtin.copy:
        src: camera_server.py
        dest: camera_server.py

    - name: Copy python socket_utils.py
      ansible.builtin.copy:
        src: socket_utils.py
        dest: socket_utils.py

    - name: Copy python pil_display.py
      ansible.builtin.copy:
        src: pil_display.py
        dest: pil_display.py

    - name: Copy camera configs
      ansible.builtin.copy:
        src: camera_configs.yaml
        dest: camera_configs.yaml

    - name: Copy pattern.png
      ansible.builtin.copy:
        src: pattern.png
        dest: pattern.png