- name: Install Everything
  become: yes # Runs commands with sudo
  hosts: cameras
  tasks:
    - name: Run apt update
      apt:
        update_cache: yes

    - name: Upgrade all packages (Optional)
      apt:
        upgrade: dist  # Performs a full upgrade, including APT itself

    - name: Install picamera
      apt:
        name:
          - python3-picamera2
        state: present
        install_recommends: no

    - name: Install pip
      apt:
        name:
          - python3-pip
        state: present
        install_recommends: no

    - name: install pyyaml
      ansible.builtin.command: python3 -m pip install pyyaml --break-system-packages

    - name: Copy python snap.py
      ansible.builtin.copy:
        src: snap.py
        dest: snap.py

    - name: Copy python camera_server.py
      ansible.builtin.copy:
        src: camera_server.py
        dest: camera_server.py

    - name: Copy python socket_utils.py
      ansible.builtin.copy:
        src: socket_utils.py
        dest: socket_utils.py

    - name: Copy camera configs
      ansible.builtin.copy:
        src: camera_configs.yaml
        dest: camera_configs.yaml