- name: My first play
  become: yes # Runs commands with sudo
  hosts: cameras
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: Hello world

    - name: Run apt update
      apt:
        update_cache: yes

    - name: Upgrade all packages (Optional)
      apt:
        upgrade: dist  # Performs a full upgrade, including APT itself