- name: Take snapshots on cameras and then copy them to localhost
  hosts: cameras
  tasks:
    - name: Take snapshot with python
      ansible.builtin.script: snap.py
      args:
        executable: python3
      register: python_snap

    - debug: msg="{{ python_snap.stdout }}"

    - name: Fetch python snapshots from remotes
      ansible.builtin.fetch:
        src: image.jpg
        dest: ./captures/image_{{inventory_hostname}}.jpg
        flat: yes
