- name: Update apt cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade all packages (Optional)
  become: yes
  apt:
    upgrade: dist  # Performs a full upgrade, including APT itself