- name: Reload udev rules
  become: true
  shell: |
    udevadm control --reload
    udevadm trigger

- name: Restart systemd-networkd
  become: true
  systemd:
    name: systemd-networkd
    state: restarted