- name: Install NVM if not already installed
  ansible.builtin.shell: |
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
  args:
    executable: /bin/bash
  environment:
    HOME: "{{ ansible_env.HOME }}"
  when: not lookup('ansible.builtin.file', ansible_env.HOME + '/.nvm', errors='ignore') is defined

- name: Ensure NVM_DIR is set in .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export NVM_DIR="$HOME/.nvm"'
    insertafter: EOF
    state: present

- name: Ensure nvm is sourced from nvm.sh
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"'
    insertafter: EOF
    state: present