- name: apt update
  hosts: raspberry_pis
  roles:
    - common

- name: pyenv setup and build
  hosts: shoulderpi
  roles:
    - shoulderpi

- name: python copy to picams
  hosts: picams
  roles:
    - picams