- name: apt update
  hosts: raspberry_pis
  roles:
    - common_apt

- name: pyenv setup and build
  hosts: shoulderpi
  roles:
    - shoulderpi

- name: python copy to picams
  hosts: picams
  roles:
    - picams

- name: pipx and poetry install
  hosts: raspberry_pis
  roles:
    - common_pipx_poetry