- name: apt update
  hosts: raspberry_pis
  roles:
    - common_apt

- name: pyenv setup and build
  hosts: shoulderpi
  roles:
    - shoulderpi_python

- name: python copy to picams
  hosts: picams
  roles:
    - picams_python

- name: pipx and poetry install
  hosts: raspberry_pis
  roles:
    - common_pipx_poetry

- name: picams networking
  hosts: picams
  roles:
    - picams_networking

- name: Wait for Pi Zeros to reboot (explicit wait before Pi 5 config)
  hosts: shoulderpi
  gather_facts: no
  tasks:
    - name: Pause for 120 seconds to allow Pi Zeros to reboot fully
      pause:
        seconds: 120

- name: shoulderpi networking
  hosts: shoulderpi
  roles:
    - shoulderpi_networking

- name: picams camera dependencies
  hosts: picams
  roles:
    - picams_picamera_2